export const addNewParcelsTemplate = [
  {
    data: [
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728313",
        Address: "7820 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728324",
        Address: "7822 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728335",
        Address: "7824 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728346",
        Address: "7826 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728357",
        Address: "7828 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
      {
        Location: "Brandywine Crossing",
        ParcelNumber: "11-5728368",
        Address: "7830 Tranquility Trl",
        City: "Brandywine",
        Zip: "20613",
        OwnerOfRecord: "Brandywine Crossing Titleholder, LLC",
        DefaultAssessor: "Prince George's County",
        DefaultCollector: "Prince George's County",
        DefaultPaymentMethod: "Pay Online",
        ParcelType: "Real Property",
        OwnershipStatus: "Owned",
        ServiceLevel: "Outsourcing With Mail Forward",
        ManagementLevel: "Active",
        TaxResponsibility: "Direct Pay",
      },
    ],
  },
];
