export const addNewParcelsTemplate = [
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
  {
    Location: "",
    ParcelNumber: "",
    Address: "",
    City: "",
    Zip: "",
    OwnerOfRecord: "",
    DefaultAssessor: "",
    DefaultCollector: "",
    DefaultPaymentMethod: "",
    ParcelType: "",
    OwnershipStatus: "",
    ServiceLevel: "",
    ManagementLevel: "",
    TaxResponsibility: "",
  },
];
