export const addNewParcelsColumns = [
  "Location",
  "ParcelNumber",
  "Address",
  "City",
  "Zip",
  "OwnerOfRecord",
  "DefaultAssessor",
  "DefaultCollector",
  "DefaultPaymentMethod",
  "ParcelType",
  "OwnershipStatus",
  "ServiceLevel",
  "ManagementLevel",
  "TaxResponsibility",
];
